# Generated by Django 3.0.5 on 2020-04-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('telephone_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('comments', models.TextField(default='')),
                ('image', models.CharField(default='https://pix10.agoda.net/hotelImages/276234/-1/13d75164caaf0f692321d155994ff9e6.jpg?s=1024x768', max_length=100)),
                ('number_of_rooms', models.IntegerField()),
                ('stars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('number_of_visitors', models.IntegerField()),
                ('bed_image', models.CharField(default='https://cdn.pixabay.com/photo/2017/01/14/12/48/hotel-1979406__340.jpg', max_length=100)),
                ('bath_image', models.CharField(default='https://cdn.pixabay.com/photo/2018/06/27/13/06/bathroom-3501553__340.jpg', max_length=100)),
                ('price', models.FloatField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
            ],
        ),
    ]
