# Generated by Django 3.0.5 on 2020-04-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200428_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='people',
            field=models.IntegerField(default=1),
        ),
    ]
