# Generated by Django 3.0.4 on 2020-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_room_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.TextField(),
        ),
    ]
