# Generated by Django 3.0.5 on 2020-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='bath_image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_image',
            field=models.TextField(default=''),
        ),
    ]
